### DISCUSSION TITLE
Reverse Proxy HTTPS

### DISCUSSION THREAD

**Discussion by Inaciomcr** [ggogel/seafile-containerized#41] [Q&A] [answered]
Hi,

I am trying to access my seafile server from https but i'm stuck.

I added the following line to the docker-compose.yml seafile server file:
```
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-data/conf.d:/etc/nginx/conf.d
      - ./nginx-data/certs:/etc/nginx/certs
      - ./nginx-data/vhost.d:/etc/nginx/vhost.d
      - ./nginx-data/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: always
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DEFAULT_EMAIL=email@provider.com
      - NGINX_PROXY_CONTAINER=nginx-proxy
```

my caddy config is:
```
 seafile-caddy:
    image: ggogel/seafile-caddy:1.0.6
#    ports:
#      - "80:80" # Point your reverse proxy to port 80 of this service
    expose:
    - "80"
    networks:
      - seafile-net
      - default
    environment:
    - VIRTUAL_PORT=80
    - VIRTUAL_HOST=site.com,192.168.0.101
```

I can access the server using http but when I try to access ussing https I receive the error :
> 500 Internal Server Error

Can you help me? I want to allow only https connection.
