### ISSUE TITLE
Notification server seems to not work properly

### ISSUE THREAD

**Issue by FluffyDiscord** [ggogel/seafile-containerized#109]
Hi, I finally got to checkout the newly enabled notification server from this https://github.com/ggogel/seafile-containerized/issues/104 and I always get Bad Request 400 no matter the JWT key I generate. The /notification/ping does work, returns "pong" as they state, but the websocket one does not.

Can you share how you set it up so it works for you?

seafile.conf
```conf
[notification]
enabled = true
host = 0.0.0.0
port = 8083
log_level = info
jwt_private_key = a24xY5.....................the_rest_of_the_key............MZ0S0=
```

docker-compose.yaml
```yaml
version: '3.8'
services:
  seafile-server:
    image: ggogel/seafile-server:10.0.1_004
    volumes:
      - /mnt/user0/appdata-array/seafile/data:/shared
    environment:
      - DB_HOST=db
      - DB_ROOT_PASSWD=db_dev
      - TIME_ZONE=Europe/Berlin
      - HTTPS=false
      - SEAFILE_SERVER_HOSTNAME=
    depends_on:
      - db
      - memcached
      - seafile-caddy
    networks:
      - seafile-net

  seahub:
    image: ggogel/seahub:10.0.1_002
    volumes:
      - /mnt/user0/appdata-array/seafile/data:/shared
      - /mnt/user0/appdata-array/seafile/avatars:/shared/seafile/seahub-data/avatars
      - /mnt/user0/appdata-array/seafile/custom:/shared/seafile/seahub-data/custom
    environment:
      - SEAFILE_ADMIN_EMAIL=
      - SEAFILE_ADMIN_PASSWORD=
    depends_on:
      - seafile-server
      - seafile-caddy
      - seahub-media
    networks:
      - seafile-net

  seahub-media:
    image: ggogel/seahub-media:10.0.1_001
    volumes:
     - /mnt/user0/appdata-array/seafile/avatars:/usr/share/caddy/media/avatars
     - /mnt/user0/appdata-array/seafile/custom:/usr/share/caddy/media/custom
    depends_on:
      - seafile-caddy
    networks:
      - seafile-net

  db:
    image: mariadb:10.11.4
    environment:
      - MYSQL_ROOT_PASSWORD=db_dev
      - MYSQL_LOG_CONSOLE=false
      - MARIADB_AUTO_UPGRADE=true
    volumes:
      - /mnt/user0/appdata-array/seafile/db:/var/lib/mysql
    networks:
      - seafile-net

  memcached:
    image: memcached:1.6.21
    entrypoint: memcached -m 1024
    networks:
      - seafile-net

  seafile-caddy:
    image: ggogel/seafile-caddy:1.1.0
    ports:
      - "8068:80" # Point your reverse proxy to port 80 of this service
    networks:
      - seafile-net
      - default

networks:
  seafile-net:
    internal: true
```

I should mention that I have seafile behind NPM (nginx proxy manager), which redirect my domain to this docker compose's port 8068. The NPM has toggled on websocket support and adding manually the proxy pass (from bellow) does not seem to help

```nginx
location = /connection {
        proxy_pass http://machineip:8068;
        proxy_http_version  1.1;
        proxy_set_header    Upgrade $http_upgrade;
        proxy_set_header    Connection "upgrade";
        proxy_set_header    Host $http_host;
        proxy_set_header    X-Real-IP $remote_addr;
    }
```
