### ISSUE TITLE
Stack error starting up Seafile 

### ISSUE THREAD

**Issue by nixfreak** [ggogel/seafile-containerized#328]
```
Failed to deploy a stack: Network seafile_seafile-net Creating Network seafile_seafile-net Created Network seafile_default Creating Network seafile_default Created Container seafile-seafile-caddy-1 Creating Container seafile-seahub-media-1 Creating Container seafile-db-1 Creating Container seafile-memcached-1 Creating Container seafile-memcached-1 Created Container seafile-seahub-media-1 Created Container seafile-seafile-caddy-1 Created Container seafile-db-1 Created Container seafile-seafile-server-1 Creating Container seafile-seafile-server-1 Created Container seafile-seahub-1 Creating Container seafile-seahub-1 Created Container seafile-seafile-caddy-1 Starting Container seafile-seahub-media-1 Starting Container seafile-db-1 Starting Container seafile-memcached-1 Starting Container seafile-seahub-media-1 Started Container seafile-memcached-1 Started Container seafile-db-1 Started Container seafile-db-1 Waiting Container seafile-seafile-caddy-1 Started Container seafile-db-1 Healthy Container seafile-seafile-server-1 Starting Container seafile-seafile-server-1 Started Container seafile-seafile-server-1 Waiting Container seafile-db-1 Waiting Container seafile-db-1 Healthy Container seafile-seafile-server-1 Error dependency failed to start: container seafile-seafile-server-1 is unhealthy
```

Do I need to setup any other containers besides this one ? 

Using Portainer created a new stack called "seafile"
copied the compose file and edited the env variables. 
Try to start and got error.

**Comment by ggogel** [comment]
I can't diagnose this issue without full logs from all containers. Seafile-server doesn't start.

**Comment by nixfreak** [comment]
Image from stack
![image](https://github.com/user-attachments/assets/2a149162-5386-4bc8-a883-36bf7a432ddd)

Server:
seafile-server-1 - 
![image](https://github.com/user-attachments/assets/285ad292-4cfc-49ca-8f30-8f57ca3ce9e1)

Server:
seafile-db-1 - 
![image](https://github.com/user-attachments/assets/787b4267-68d1-41f0-bfa0-0ee0c14d1e72)

Not sure why the database doesn't like the password 

Pasting the full compose file 

```
version: '3.8'
services:
  seafile-server:
    image: ggogel/seafile-server:11.0.12
    volumes:
      - seafile-data:/shared
    environment:
      - DB_HOST=db
      - DB_ROOT_PASSWD="TpRkuwR2zAMcskAPm3trnbxTmTDzR7"
      - TIME_ZONE=America/Chicago
      - HTTPS=true
      - SEAFILE_URL=cha0snet.zapto.org # Mandatory on first deployment!
    networks:
      - seafile-net
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8082"]
      interval: 10s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  seahub:
    image: ggogel/seahub:11.0.12
    volumes:
      - seafile-data:/shared
      - seahub-avatars:/shared/seafile/seahub-data/avatars
      - seahub-custom:/shared/seafile/seahub-data/custom
    environment:
      - SEAFILE_ADMIN_EMAIL=me@example.com
      - SEAFILE_ADMIN_PASSWORD=Pm3trnbxTmTDzR7
      -     networks:
      - seafile-net
    depends_on:
      db:
        condition: service_healthy
      seafile-server:
        condition: service_healthy
    restart: unless-stopped

  seahub-media:
    image: ggogel/seahub-media:11.0.12
    volumes:
      - seahub-avatars:/usr/share/caddy/media/avatars
      - seahub-custom:/usr/share/caddy/media/custom
    networks:
      - seafile-net
    restart: unless-stopped

  db:
    image: mariadb:10.11.9
    environment:
      - MYSQL_ROOT_PASSWORD="TpRkuwR2zAMcskAPm3trnbxTmTDzR7"
      - MYSQL_LOG_CONSOLE=true
      - MARIADB_AUTO_UPGRADE=true
    volumes:
      - seafile-mariadb:/var/lib/mysql
    networks:
      - seafile-net
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  memcached:
    image: memcached:1.6.31
    entrypoint: memcached -m 1024
    networks:
      - seafile-net
    restart: unless-stopped

  seafile-caddy:
    image: ggogel/seafile-caddy:2.8.4
    ports:
      - "80:80" # Point your reverse proxy to port 80 of this service
    networks:
      - seafile-net
      - default
    restart: unless-stopped

networks:
  seafile-net:
    internal: true

volumes:
  seafile-data:
  seafile-mariadb:
  seahub-avatars:
  seahub-custom:
```
