### ISSUE TITLE
seafile-server Fails to Connect to db

### ISSUE THREAD

**Issue by ozpinu** [ggogel/seafile-containerized#341]
I am deploying this from scartch and the seafile-server container fails during the initial setup with an “Access denied” error when attempting to connect to the seafile-db service (MariaDB). The issue appears to be related to user authentication or database configuration.

## Error Logs

seafile-server **container logs**:
```
Failed to connect to mysql server using user "seafile" and password "***": Access denied for user 'seafile'@'192.168.90.44' (using password: YES)

Traceback (most recent call last):
  File "/scripts/start.py", line 66, in <module>
    main()
  File "/scripts/start.py", line 50, in main
    init_seafile_server()
  File "/scripts/bootstrap.py", line 80, in init_seafile_server
    call('{} auto -n seafile'.format(setup_script), env=env)
  File "/scripts/utils/__init__.py", line 70, in call
    return subprocess.check_call(*a, **kw)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/opt/seafile/seafile-server-11.0.12/setup-seafile-mysql.sh auto -n seafile' returned non-zero exit status 255.
```

seafile-db **container logs**:
```
[Warning] Aborted connection to db: 'seahub_db' user: 'seafile' host: '192.168.90.44' (Got an error reading communication packets)
[Warning] Aborted connection to db: 'ccnet_db' user: 'seafile' host: '192.168.90.44' (Got an error reading communication packets)
```

## Steps to Reproduce

1. Deploy the following Docker Compose stack:
```
version: "3.9"
services:
  seafile-server:
    image: ggogel/seafile-server:11.0.12
    container_name: seafile-server
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - t3_proxy
    environment:
      - DB_HOST=seafile-db
      - DB_ROOT_PASSWD=db_dev
      - TIME_ZONE=$TZ
      - HTTPS=true
      - SEAFILE_URL=seafile.$DOMAINNAME # Mandatory on first deployment!
    volumes:
      - $DOCKERDIR/appdata/seafile/data:/shared
    depends_on:
      seafile-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8082"]
      interval: 10s
      timeout: 10s
      retries: 3

  seahub:
    image: ggogel/seahub:11.0.12
    container_name: seahub
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - t3_proxy
    environment:
      - SEAFILE_ADMIN_EMAIL=hello@admin.com
      - SEAFILE_ADMIN_PASSWORD=password
    volumes:
      - $DOCKERDIR/appdata/seafile/data:/shared
      - $DOCKERDIR/appdata/seafile/seahub-avatars:/shared/seafile/seahub-data/avatars
      - $DOCKERDIR/appdata/seafile/seahub-custom:/shared/seafile/seahub-data/custom
    depends_on:
      seafile-db:
        condition: service_healthy
      seafile-server:
        condition: service_healthy

  seahub-media:
    image: ggogel/seahub-media:11.0.12
    container_name: seahub-media
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - t3_proxy
    volumes:
      - $DOCKERDIR/appdata/seafile/seahub-avatars:/shared/seafile/seahub-data/avatars
      - $DOCKERDIR/appdata/seafile/seahub-custom:/shared/seafile/seahub-data/custom

  seafile-db:
    image: mariadb:10.11.9
    container_name: seafile-db
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - t3_proxy
    environment:
      - MYSQL_ROOT_PASSWORD=db_dev
      - MYSQL_LOG_CONSOLE=true
      - MARIADB_AUTO_UPGRADE=true
    volumes:
      - $DOCKERDIR/appdata/seafile/db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 10s
      retries: 3

  seafile-memcached:
    image: memcached:1.6.32
    container_name: seafile-memcached
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - t3_proxy
    entrypoint: memcached -m 1024

  seafile-caddy:
    image: ggogel/seafile-caddy:2.8.4
    container_name: seafile-caddy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - t3_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.seafile-rtr.entrypoints=websecure"
      - "traefik.http.routers.seafile-rtr.rule=Host(`seafile.$DOMAINNAME`)"
      - "traefik.http.routers.seafile-rtr.middlewares=chain-authelia@file"
      - "traefik.http.routers.seafile-rtr.service=seafile-svc"
      - "traefik.http.services.seafile-svc.loadbalancer.server.port=80"

networks:
  t3_proxy:
    driver: bridge
```

2. Start the containers using docker-compose up -d.
3. Observe the logs for seafile-server and seafile-db

## Expected Behaviour

- The seafile-server container should connect to the seafile-db service successfully and complete the setup process.

## Actual Behaviour

- seafile-server fails to connect to seafile-db, resulting in an “Access denied” error.
- seafile-db logs show aborted connections with the message Got an error reading communication packets.

## Environment

- seafile-server Docker Image: ggogel/seafile-server:11.0.12
- seafile-db Docker Image: mariadb:10.11.9
- Docker Version: Docker version 27.3.1, build ce12230
- Host OS: Debian GNU/Linux bookworm 12.8 x86_64
- Filesystem: ZFS

If you need additional logs or configuration details, please let me know. Thank you for your support!
