### ISSUE TITLE
Seahub stuck Waiting for initialization by seafile-server...

### ISSUE THREAD

**Issue by Laikar** [ggogel/seafile-containerized#63]
I have tried to setup seafile using your docker compose example but something seems to be not working well.
Visiting the url iset yields nothing, and on the docker compsoe logs the seahub seems to be stuck  " Waiting for initialization by seafile-server..."

This is the docker compose file i am using https://pastebin.com/FySUt6Hi
And this is the ouput of docker compose logs https://pastebin.com/6deMyZBB

**Comment by Laikar** [comment]
I seem to not know how to handle volumes, cause replacing every single volume with a bind mount solve the issue,
(There was also an error on the mount path for seahub, but fixing it ddidn't solve my issue).
This is the compose file i used 
```
version: '3.8'
services:
  seafile-server:
    image: ggogel/seafile-server:9.0.9
    volumes:
      - /storage/data/seafile/seafile:/shared
    environment:
      - DB_HOST=db
      - DB_ROOT_PASSWD=password
      - TIME_ZONE=Europe/Madrid
      - HTTPS=false
      - SEAFILE_SERVER_HOSTNAME=seafile.test.laikar.moe # Mandatory on first deployment!
    depends_on:
      - db
      - memcached
      - seafile-caddy
    networks:
      seafile_network:


  seahub:
    image: ggogel/seahub:9.0.9
    volumes:
      - /storage/data/seafile/seafile:/shared
      - /storage/data/seafile/media/avatars:/shared/seafile/seahub-data/avatars
      - /storage/data/seafile/media/custom:/shared/seafile/seahub-data/custom
    environment:
      - SEAFILE_ADMIN_EMAIL=david@laikar.moe
      - SEAFILE_ADMIN_PASSWORD=adminpass
    depends_on:
      - seafile-server
      - seafile-caddy
      - seahub-media
    networks:
      seafile_network:


  seahub-media:
    image: ggogel/seahub-media:9.0.9
    volumes:
     - /storage/data/seafile/media/avatars:/usr/share/caddy/media/avatars
     - /storage/data/seafile/media/custom:/usr/share/caddy/media/custom
    depends_on:
      - seafile-caddy
    networks:
      seafile_network:


  db:
    image: mariadb:10.7.6
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - /storage/data/seafile/mariadb:/var/lib/mysql
    networks:
      seafile_network:


  memcached:
    image: memcached:1.6.17
    entrypoint: memcached -m 1024
    networks:
      seafile_network:


  seafile-caddy:
    image: ggogel/seafile-caddy:1.0.6
    expose:
      - 80
    networks:
      seafile_network:
        ipv4_address: 10.3.1.1


networks:
  seafile_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.3.0.0/16
          gateway: 10.3.0.1


```
