### ISSUE TITLE
problems with TIME_ZONE on seahub container

### ISSUE THREAD

**Issue by ma4a** [ggogel/seafile-containerized#71]
Hi,

If TIME_ZONE is set in docker-compose environment parameters the script https://github.com/ggogel/seafile-containerized/blob/master/seahub/scripts/create_data_links.sh at container startup fails with `invalid time zone` error.
Taking a look inside the failed but running seahub container, I can see that there is no 'zoneinfo' folder where the script is checking for if the named zone exists: 
`ls: /usr/share/zoneinfo/*: No such file or directory`

I finally found a solution that works:
I mounted the zoneinfo folder from the host inside the seahub container read only:
```yaml
  seahub:
    image: ggogel/seahub
    container_name: seahub
    restart: unless-stopped
    volumes:
      - seafile-data:/shared
      - seahub-avatars:/shared/seafile/seahub-data/avatars
      - seahub-custom:/shared/seafile/seahub-data/custom
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
    environment:
      - SEAFILE_ADMIN_EMAIL=
      - SEAFILE_ADMIN_PASSWORD=
      - TIME_ZONE=Europe/Berlin
```

After that and a container rebuild, seahub container logs have the correct time. :)
