### ISSUE TITLE
Communication problems between containers

### ISSUE THREAD

**Issue by fakuivan** [ggogel/seafile-containerized#94]
I tried to sync a library between clients but I'm getting the following errors:

![image](https://user-images.githubusercontent.com/15100012/232818311-aa713915-0fa1-421a-91fe-9c503fabd10e.png)

(the gui reports "server error")

seafile.log shows these repeated lines:

```text
[04/18/23 12:00:47] Transfer repo 'ee994f7a': ('normal', 'check') --> ('normal', 'commit')
[04/18/23 12:00:47] Transfer repo 'ee994f7a': ('normal', 'commit') --> ('normal', 'fs')
[04/18/23 12:00:47] Transfer repo 'ee994f7a': ('normal', 'fs') --> ('normal', 'data')
[04/18/23 12:00:47] Bad response code for GET http://172.22.172.137/seafhttp/repo/ee994f7a-ea6f-4e7f-9cdf-b86ba20061f9/block/8b36fe37afd9d07a3c58f6c7ea0945a4ccce9077: 500.
[04/18/23 12:00:47] Transfer failed.
[04/18/23 12:00:47] libcurl failed to GET http://172.22.172.137/seafhttp/repo/ee994f7a-ea6f-4e7f-9cdf-b86ba20061f9/block/a51917a0349d6fe44bedc272e269fcee6ac41fff: Failed writing received data to disk/application.
[04/18/23 12:00:47] Transfer failed.
[04/18/23 12:00:47] libcurl failed to GET http://172.22.172.137/seafhttp/repo/ee994f7a-ea6f-4e7f-9cdf-b86ba20061f9/block/4bfef7d920f0e7f184f132eecfd7220fbfa87f7f: Failed writing received data to disk/application.
[04/18/23 12:00:47] Transfer failed.
[04/18/23 12:00:47] libcurl failed to GET http://172.22.172.137/seafhttp/repo/ee994f7a-ea6f-4e7f-9cdf-b86ba20061f9/block/76c6de1c0ea6e4ce4c66959ea930ae2b45c182f3: Failed writing received data to disk/application.
[04/18/23 12:00:47] Transfer failed.
[04/18/23 12:00:47] Transfer repo 'ee994f7a': ('normal', 'data') --> ('error', 'finished')
[04/18/23 12:00:47] Repo 'Trabajos ingeniería' sync state transition from downloading to 'error': 'Server error'.
```

`docker compose logs` shows that there's apparently some communication errors between the different containers:

```
seafile-db-1              | 2023-04-18 14:51:56 3 [Warning] Aborted connection 3 to db: 'unconnected' user: 'root' host: '172.20.0.3' (Got an error reading communication packets)
seafile-db-1              | 2023-04-18 14:51:56 4 [Warning] Aborted connection 4 to db: 'ccnet_db' user: 'seafile' host: '172.20.0.3' (Got an error reading communication packets)
seafile-db-1              | 2023-04-18 14:51:56 5 [Warning] Aborted connection 5 to db: 'seafile_db' user: 'seafile' host: '172.20.0.3' (Got an error reading communication packets)
seafile-db-1              | 2023-04-18 14:51:56 6 [Warning] Aborted connection 6 to db: 'seahub_db' user: 'seafile' host: '172.20.0.3' (Got an error reading communication packets)
...
seafile-seafile-caddy-1   | {"level":"error","ts":1681829569.7380185,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"write tcp 172.19.0.2:80->172.22.82.61:64194: write: broken pipe"}
seafile-seafile-caddy-1   | {"level":"error","ts":1681829601.3078158,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"write tcp 172.19.0.2:80->172.22.82.61:64205: write: connection reset by peer"}
seafile-seafile-caddy-1   | {"level":"error","ts":1681829601.3115315,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"write tcp 172.19.0.2:80->172.22.82.61:64187: write: connection reset by peer"}
seafile-seafile-server-1  | 2023-04-18 15:36:50 ../common/block-backend-fs.c(237): [block bend] Failed to stat block ee994f7a-ea6f-4e7f-9cdf-b86ba20061f9:8b36fe37afd9d07a3c58f6c7ea0945a4ccce9077 at /opt/seafile/seafile-data/storage/blocks/ee994f7a-ea6f-4e7f-9cdf-b86ba20061f9/8b/36fe37afd9d07a3c58f6c7ea0945a4ccce9077: No such file or directory.
seafile-seahub-1          | 2023-04-18 15:47:28,618 [WARNING] django.request:224 log_response Not Found: /notification/ping
seafile-seahub-1          | 2023-04-18 15:47:28,618 [WARNING] django.request:224 log_response Not Found: /notification/ping
```

I'm guessing the communication between the containers is not the best for some reason, and at some point the server failed to recieve a block that it thinks it has. Here's my compose config file:

```yaml
version: '3.8'
services:
  seafile-server:
    image: ggogel/seafile-server:10.0.1
    volumes:
    - /mnt//cami-uwu/seafile/shared:/shared
    environment:
      DB_HOST: db
      DB_ROOT_PASSWD: db_dev
      TIME_ZONE: Etc/UTC
      HTTPS: 'false'
      SEAFILE_SERVER_HOSTNAME: 172.22.172.137
    depends_on:
    - db
    - seafile-caddy
    networks:
    - seafile-net
    restart: unless-stopped

  seahub:
    image: ggogel/seahub:10.0.1
    volumes:
    - /mnt/cami-uwu/seafile/shared:/shared
    environment:
      SEAFILE_ADMIN_EMAIL: fakuivan+admin@gmail.com
      SEAFILE_ADMIN_PASSWORD: CjEj54TgSfysmaRh
    depends_on:
    - seafile-server
    - seafile-caddy
    - seahub-media
    - memcached
    networks:
    - seafile-net
    restart: unless-stopped

  seahub-media:
    image: ggogel/seahub-media:10.0.1
    volumes:
    - /mnt/cami-uwu/seafile/shared/seafile/seahub-data/avatars:/usr/share/caddy/media/avatars
    - /mnt/cami-uwu/seafile/shared/seafile/seahub-data/custom:/usr/share/caddy/media/custom
    depends_on:
    - seafile-caddy
    networks:
    - seafile-net
    restart: unless-stopped

  db:
    image: mariadb:10.7.8
    environment:
      MYSQL_ROOT_PASSWORD: db_dev
      MYSQL_LOG_CONSOLE: 'true'
    hostname: db
    volumes:
    - /mnt/cami-uwu/seafile/mariadb:/var/lib/mysql
    networks:
    - seafile-net
    restart: unless-stopped

  memcached:
    image: memcached:1.6.19
    entrypoint: memcached -m 1024
    networks:
    - seafile-net
    restart: unless-stopped

  seafile-caddy:
    image: ggogel/seafile-caddy:1.0.8
    ports:
    - 80:80
    networks:
      seafile-net: null
      default: null
    restart: unless-stopped

networks:
  seafile-net:
    internal: true
```
